apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
        containers:
        - name: api-gateway-service
          image: gcr.io/go-micro-test/api-gateway-service:latest
          imagePullPolicy: Always
          env:
          - name: MICRO_REGISTRY
            value: "kubernetes"
          - name: PORT
            value: "8080"
          ports:
          - containerPort: 8080
            name: service-port
